create(bll:FTBSkiesExpert {name: "Black Laser Lens"})
create(co:FTBSkiesExpert {name: "Crude Oil"})
create(fuel:FTBSkiesExpert {name: "Fuel"})
create(gs:FTBSkiesExpert {name: "Gaseous Source"})
create(ls:FTBSkiesExpert {name: "Liquified Source"})
create(mob:FTBSkiesExpert {name: "Mob"})
create(ps:FTBSkiesExpert {name: "Pink Slime"})
create(seed:FTBSkiesExpert {name: "Seed"})
create(vo:FTBSkiesExpert {name: "Vegtable Oil"})
