site_name: Minecraft Recipes
site_url: https://minecraft.stefhen.com
repo_url: https://github.com/res0nat0r/minecraft
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Nunito
  extra:
    analytics:
      provider: google
      property: G-YQBCWMP6WS
  extra_css:
    - stylesheets/extra.css
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark-blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark-blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Light Mode
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
