site_name: Minecraft Recipes
site_url: https://res0nat0r.github.io/minecraft
theme:
  name: material
  features:
    - navigation.instant
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
